services:
  openvscode-server:
    image: formattedd/code-server
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
    volumes:
      - "./data/openvscode:/home/coder:cached"
      # - ../projects:/projects
    ports:
      - "3000:3000"
    init: true
    tty: true
    stdin_open: true
    restart: unless-stopped
